language: ruby
cache: bundler
sudo: false
before_install:
  - gem install bundler

install:
  - bundle install --without debugger

script:
  - bundle exec ruby test/suite.rb

notifications:
  email:
  - ngiger@ywesee.com
rvm:
  - ruby-head
  - 2.2.3
  - 2.1.7
  - 2.0.0
  - 1.9.3
  - 1.8.7
matrix:
  allow_failures:
    - rvm: ruby-head
